[package]
authors = ["ubugeeei"]
name = "rusty-discord-invite-bot"
version = "0.1.1"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.14"
poise = "0"
thiserror = "1.0.30"
tokio = { version = "1.16.1", features = ["rt-multi-thread"] }
